TMP_DIR: '~/nimir_git/posts_monster/data/tmp/'
DATA_DIR: '~/nimir_git/posts_monster/data/posts/'

news_host: 'http://feed.omgili.com/5Rh5AMTrc4Pv/mainstream/posts/1464993367242.zip'

redis:
  host_name: 'localhost'
  port: '6379'